
class Character{
  String name,

    image, 

    //Counters
    imgCon1,
    imgCon2,
    imgCon3,

    //Syn
    imgSyn1,
    imgSyn2,
    imgSyn3,



    description,

    charClass,
    charRank,
    charRegion,



    abilityName1,
    abilityDes1,
    abilityImg1,
    abilityCost1,

    abilityName2,
    abilityDes2,
    abilityImg2,
    abilityCost2,

    abilityName3,
    abilityDes3,
    abilityImg3,
    abilityCost3,


    abilityName4,
    abilityDes4,
    abilityImg4,
    abilityCost4;

  double rating;

  //add this for charges
  int charge1;
  int charge2;
  int charge3;
  int charge4;

  Character(this.name, this.charClass, this.charRank, this.charRegion, this.image, this.description, this.abilityCost1, this.abilityCost2, this.abilityCost3, this.abilityCost4, this.abilityDes1, this.abilityDes2, this.abilityDes3, this.abilityDes4,
   this.abilityImg1, this.abilityImg2, this.abilityImg3, this.abilityImg4, this.abilityName1, this.abilityName2, this.abilityName3, this.abilityName4, this.rating, this.imgSyn1, this.imgSyn2, this.imgSyn3, this.imgCon1, this.imgCon2, this.imgCon3, this.charge1, this.charge2, this.charge3, this.charge4);
}

final List<Character> characters = [
    Character('Sage',
      'Sentinel',
      'S Tier',
      'China',
      'res/sage.jpg',
      'Valorant Sage Signature Ability available at the start of the round called Healing Orb Equip a healing orb. Fire with your crosshairs over a damaged ally to activate a heal-over-time on them. Alternate fire while Sage is damaged to activate a self heal-over-time. You also have an Ultimate Ability called Resurrection, which charges up from kills, you can also purchase two more abilities called Barrier Orb and Slow Orb between rounds.',
      '300', 
      '100', 
      'Free', 
      '7 Points', 
      'Equip a barrier orb. Fire places a solid wall. Alternate fire rotates the targeter. Conjure a large, solid wall. Right-click to rotate the wall before casting.', 
      'Equip a slowing orb. Fire to throw a slowing orb forward that detonates upon landing, creating a lingering field that slows and grounds players caught inside of it. Moving through the Slow Orb will make noise. Cast out a radianite orb that breaks into a slowing field upon impact with the ground. All caught in the field are slowed, grounded, and make noise when moving.', 
      'Equip a healing orb. Fire with your crosshairs over a damaged ally to activate a heal-over-time on them. Alternate fire while Sage is damaged to activate a self heal-over-time. Heal an ally or yourself to full health over a few seconds.', 
      'Equip a resurrection ability. Fire with your crosshairs placed over a dead ally to begin resurrecting them. After a brief channel, the ally will be brought back to life with full health. Does NOT recover Armor! Target a friendly corpse. After a short delay, revive them with full health.', 
      'res/Sage_BarrierOrb.png',
      'res/Sage_HealingOrb.png',
      'res/Sage_Resurrection.png',
      'res/Sage_SlowOrb.png',
      'Barrier Orb', 
      'Slow Orb', 
      'Healing Orb', 
      'Resurrection', 
      3.5,
      'res/breach.jpg',
      'res/raze.jpg',

      'res/White.png',

      'res/raze.jpg',

      'res/White.png',
      'res/White.png',
      
      1,
      2,
      1,
      1,
      ),

    Character('Breach', 
    'Initiator',
    'A Tier',
    '????',
    'res/breach.jpg', 
    'Valorant Breach Signature Ability available at the start of the round called Fault Line Equip a seismic blast. Hold Fire to increase the distance. Release to set off the quake, dazing all players in its zone and in a line up to the zone. You also have an Ultimate Ability called Rolling Thunder, which charges up from kills, you can also purchase two more abilities called Aftershock and Flash Point between rounds.', 
    '100', 
    '200', 
    'Free', 
    '7 Points', 
    'Equip a fusion charge. Fire the charge to set a slow-acting burst through the wall. The burst does heavy damage to anyone caught in its area.', 
    'Equip a blinding charge. Fire the charge to set a last-acting burst through the wall. The charge detonates to blind all players looking at it. Flash Duration: 2 Seconds', 
    'Equip a seismic blast. Hold Fire to increase the distance. Release to set off the quake, dazing all players in its zone and in a line up to the zone. Stun Duration: 3 Seconds', 
    'Equip a seismic charge. Fire to send a cascading quake through all terrain in a large cone. The quake dazes and knocks up anyone caught in it.', 
    'res/Breach_Aftershock.png',
    'res/Breach_FaultLine.png',
    'res/Breach_FlashPoint.png',
    'res/Breach_RollingThunder.png',
    'Aftershock', 
    'Flash Point', 
    'Fault Line', 
    'Rolling Thunder',
    3.5,

    'res/White.png',
    'res/White.png',
    'res/White.png',

    'res/White.png',
    'res/White.png',
    'res/White.png',
    1,
    1,
    1,
    1,    ),

    Character('Brimstone',
    'Controller',
    'A Tier',
    'United States', 
    'res/Brimstone.jpg', 
    'Valorant Brimstone Signature Ability available at the start of the round called Sky Smoke Equip a tactical map. Fire to set locations where Brimstones smoke clouds will land. Alternate Fire to confirm, launching long-lasting smoke clouds that block vision in the selected area. You also have an Ultimate Ability called Orbital Strike, which charges up from kills, you can also purchase two more abilities called Stim Beacon and Incendiary between rounds.', 
    '100', 
    '200',
    'Free', 
    '6 Points', 
    'Equip a Stim Beacon. Fire to toss the stim beacon in front of Brimstone. Upon landing, the stim beacon will create a field that grants players Rapid Fire. Gain increased: Fire Rate | Reload Speed | Recoil Spread Recovery. Lasts an additional 4 seconds after leaving the Stim Beacon range. Target a nearby location to call in a Stim Beacon, giving all players near it Rapidfire.', 
    'Equip an Incendiary grenade launcher. Fire to launch a grenade that detonates as it comes to a rest on the floor, creating a lingering fire zone that damages players within the zone. 5 Damage Per Tick. Launch an incendiary grenade that deploys a damaging field of fire.', 
    'Equip a tactical map. Fire to set locations where Brimstones smoke clouds will land. Alternate Fire to confirm, launching long-lasting smoke clouds that block vision in the selected area. Use your map to call in orbital deployment smokescreens that obscure vision. Click to set the locations, and confirm to launch.', 
    'Equip a tactical map. Fire to launch a lingering orbital strike laser at the selected location dealing high damage over-time to players caught in the selected area. Use your map to target a location, launching a devastating orbital strike that pulses for high damage over several seconds.', 
    'res/Brimstone_Incendiary.png',
    'res/Brimstone_OrbitaStrike.png',
    'res/Brimstone_SkySmoke.png',
    'res/Brimstone_StimBeacon.png',
    'Stim Beacon', 
    'Incendiary', 
    'Sky Smoke', 
    'Orbital Strike',
    3.5,
    'res/sova.jpg',

    'res/White.png',
    'res/White.png',

    'res/omen.jpg',

    'res/White.png',
    'res/White.png',
    1,
    1,
    3,
    1,   ),

    Character('Cypher',
    'Sentinel',
    'A Tier',
    'Morocco', 
    'res/cypher.jpg',
    'Valorant Cypher Signature Ability available at the start of the round called Spycam Equip a spycam. Fire to place the spycam at the targeted location. REUSE this ability to take control of the cameras view. While in control of the camera. Fire to shoot a marking dart. This dart will reveal the location of any player struck by the dart. You also have an Ultimate Ability called Neural Theft, which charges up from kills, you can also purchase two more abilities called Trapwire and Cyber Cage between rounds.', 
    '200', 
    '100', 
    'Free', 
    '7 Point',
    'Equip a trapwire. Fire to place a destructible and covert tripware at the targeted location, creating a line that spans between the placed location and the wall opposite. Enemy players who cross a tripwire will be tethered, revealed, and dazed after a short period if they do not destroy the device in time. This ability can be picked up to be redeployed. Place a stealthed tripwire between two walls. Triggering enemies are restrained and revealed for a short time. If the trap is not destroyed, it activates to daze the trapped victim. Can be picked up.', 
    'Equip a cyber cage. Fire to toss the cyber cage in front of Cypher. Activate to create a zone that blocks vision and slows enemies who pass through it.Toss out a remote activation trap. Reactivate to create a cage that slows enemies who pass through it. Look at a trap and press USE to detonate it, or hold ACTIVATE to detonate all.', 
    'Equip a spycam. Fire to place the spycam at the targeted location. REUSE this ability to take control of the cameras view. While in control of the camera. Fire to shoot a marking dart. This dart will reveal the location of any player struck by the dart. Place a remote camera. After placing, reactivate to view the video feed. Left click while in camera to fire a tracking dart. Recharges when picked up or killed.', 
    'Instantly use on a dead enemy player in your crosshairs to reveal the location of all living enemy players. Extract information from the corpse of an enemy, revealing the location of their living allies.',  
    'res/Cypher_CyberCage.png',
    'res/Cypher_NeuralTheft.png',
    'res/Cypher_Spycam.png',
    'res/Cypher_Trapwire.png',
    'Trap Wire', 
    'Cyber Cage', 
    'Spycam', 
    'Neural Theft',
    3.5,
    'res/jett.jpg',

    'res/White.png',
    'res/White.png',

    'res/cypher.jpg',

    'res/White.png',
    'res/White.png',
    2,
    2,
    1,
    1,   ),

    Character('Sova', 
    'Initiator',
    'A Tier',
    'Russia',
    'res/sova.jpg', 
    'Valorant Sova Signature Ability available at the start of the round called Recon Bolt Equip a bow with recon bolt. Fire to send the bolt forward activating upon collision and revealing the location of nearby enemies caught in the line of sight of the bolt. Enemies can destroy this bolt. Hold Fire to extend the range of the projectile. Alternate Fire to add up to two bounces to this arrow. You also have an Ultimate Ability called Hunter’s Fury, which charges up from kills, you can also purchase two more abilities called Owl Drone and Shock Bolt between rounds.', 
    '300', 
    '100', 
    'Free', 
    '7 Points',
    'Equip a owl drone. Fire to deploy and take control of movement of the drone. While in control of the drone, Fire to shoot a marking dart. This dart will reveal the location of any player struck by the dart. Deploy a pilotable drone that can fire a dart that will reveal enemies who are hit.', 
    'Equip a bow with shock bolt. Fire to send the explosive bolt forward detonating upon collision and damaging players nearby. Hold Fire to extend the range of the projectile. Alternate Fire to add up to two bounces to this arrow. Fire an explosive bolt that emits a damaging pulse of static energy upon impact.', 
    'Equip a bow with recon bolt. Fire to send the bolt forward activating upon collision and revealing the location of nearby enemies caught in the line of sight of the bolt. Enemies can destroy this bolt. Hold Fire to extend the range of the projectile. Alternate Fire to add up to two bounces to this arrow. Fire a bolt that deploys a sonar emitter. The sonar pings tag nearby enemies, causing them to be revealed. Can be destroyed.', 
    'Equip a bow with three long-rage, wall-piercing energy blasts. Fire to release an blast in a line in front of Sova dealing damage and revealing the location of enemies caught in the line. This ability can be RE-USED up to two more times while the ability timer is active. Fire up to three deadly energy blasts that spear across the entire map. Each hit enemy takes heavy damage and is marked.',  
    'res/Sova_HunterFury.png',
    'res/Sova_OwlDrone.png',
    'res/Sova_ReconBolt.png',
    'res/Sova_ShockBolt.png', 
    'Owl Drone', 
    'Shock Bolt', 
    'Recon Bolt', 
    'HuntersFurry',
    3.5,

    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    1,
    2,
    1,
    1,   ),

    Character('Raze',
    'Duelist',
    'S Tier',
    'El Salvador', 
    'res/raze.jpg', 
    'Valorant Raze Signature Ability available at the start of the round called Blast Pack Instantly throw a Blast Pack that will stick to surfaces. Re-us the ability after deployment to detonate, damaging and moving anything hit. Raze isnt damaged by this ability, but will still take fall damage if launched up far enough. You also have an Ultimate Ability called Showstopper, which charges up from kills, you can also purchase two more abilities called Boom Bot and Paint Shells between rounds.', 
    '100', 
    '200',
    'Free', 
    '6 Points', 
    'Equip a Boom Bot. Fire will deploy the bot, causing it to travel in a straight line on the ground, bouncing off walls. The Boom Bot will lock on to any enemies in it frontal cone and chase them, exploding for heavy damage if it reaches them.', 
    'Equip a cluster grenade. Fire to throw the grenade, which does damage and creates sub-munitions, each doing damage to anyone in their range.', 
    'Instantly throw a Blast Pack that will stick to surfaces. Re-us the ability after deployment to detonate, damaging and moving anything hit. Raze isnt damaged by this ability, but will still take fall damage if launched up far enough.', 
    'Equip a single-use rocket launcher with the ability to one-shot enemies. Damage from this ability is consistent throughout the entire blast radius.', 
    'res/Raze_BlastPack.png',
    'res/Raze_BoomBot.png',
    'res/Raze_PaintShells.png',
    'res/Raze_Showstopper.png', 
    'Boom Bot', 
    'Paint Shells', 
    'Blast Pack', 
    'Showstopper',
    3.5,

    'res/omen.jpg',
    'res/jett.jpg',
    'res/breach.jpg',

    'res/omen.jpg',
    'res/White.png',
    'res/White.png',
    1,
    1,
    1,
    1,  ),

    Character('Phoenix',
    'Duelist',
    'A Tier',
    'United Kingdom', 
    'res/phoenix.jpg', 
    'Valorant Phoenix Signature Ability available at the start of the round called Curveball Equip a flare orb that takes a curving path and detonates shortly after throwing. Fire to curve the flare orb to the left, detonating the blinding any player who sees the orb. Alternate fire to curve the flare orb to the right.Instantly propel in the direction she is moving. If Jett is standing still, she will propel forward. You also have an Ultimate Ability called Run it Back, which charges up from kills, you can also purchase two more abilities called Blaze and Hot Hands between rounds.', 
    '200', 
    '100', 
    'Free',
    '6 Points', 
    'Equip a fireball. Fire to throw a fireball that explodes after a set amount of time or upon hitting the ground, creating a lingering fire zone that damages enemies. Phoenix Heals from the Fire Damage of this Ability. Cast out a flame wall that blocks vision and damages anyone passing through it. You can bend the wall when casting by turning while holding left click.', 
    'Equip a flame wall. Fire to create a line of flames that moves forward creating a wall that blocks vision and damages players passing through it. Hold Fire to bend the wall in the direction of your crosshair. Phoenix Heals from the Fire Damage of this Ability. Throw a fireball that explodes after a delay or upon impact with the ground. The fire zone damages enemies, and heals you.', 
    'Equip a flare orb that takes a curving path and detonates shortly after throwing. Fire to curve the flare orb to the left, detonating the blinding any player who sees the orb. Alternate fire to curve the flare orb to the right.Instantly propel in the direction she is moving. If Jett is standing still, she will propel forward. A flare orb that takes a curving path and detonates shortly after throwing.', 
    'Instantly place a marker at Phoenixs location. While this ability is active, dying or allowing the timer to expire will end this ability and bring Phoenix back to this location with full health. Does NOT recover Armor! Mark your current location. If you die during this abilitys duration, or when this abilitys duration expires, youll be reborn at the marked location with full health.', 
    'res/Phoenix_Blaze.png',
    'res/Phoenix_Curveball.png',
    'res/Phoenix_HotHands.png',
    'res/Phoenix_RunitBack.png',
    'Blaze', 
    'Hot hand', 
    'Curveball', 
    'Run it back',
    3.5,

    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    1,
    1,
    2,
    1,   ),

    Character('Jett',
    'Duelist',
    'B Tier',
    'South Korea', 
    'res/jett.jpg', 
    'Valorant Jett Signature Ability available at the start of the round called Tailwind Instantly propel in the direction she is moving. If Jett is standing still, she will propel forward. You also have an Ultimate Ability called Blade Storm, which charges up from kills, you can also purchase two more abilities called Cloudburst and Updraft between rounds.', 
    '100', 
    '200', 
    'Free', 
    '6 Point', 
    'Instantly throw a projectile that expands into a brief vision cloud on impact with a surface. Hold the ability key to curve the cloud in the direction of your crosshair. Throw out a cloud of fog that obscures vision on impact. Hold down the ability button to bend the cloud’s in-flight trajectory.', 
    'Instantly propel Jett high into the air. After a brief wind up, propel yourself upwards.', 
    'Instantly propel in the direction she is moving. If Jett is standing still, she will propel forward. Immediately dash a short distance in the direction you’re moving.', 
    'Equip a set of highly accurate throwing knives that recharge on an opponent. Fire to throw a single knife at your target. Alternative Fire to throw all remaining daggers at your target. Arm yourself with several deadly throwing knives that deal moderate damage and kill on headshots. Scoring a kill restores all daggers. Left click throws a single dagger. Right click throws all remaining daggers in a short-ranged burst.', 
    'res/Jett_BladeStorm.png',
    'res/Jett_Cloudburst.png',
    'res/Jett_Tailwind.png',
    'res/Jett_Updraft.png',
    'Cloudburst', 
    'Updraft', 
    'Tailwind', 
    'Blade Strom',
    3.5,

    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    'res/White.png',
    3,
    2,
    1,
    1,  ),

    Character('Viper',
    'Controller',
    'B Tier',
    'United States', 
    'res/viper.jpg', 
    'Valorant Viper Signature Ability available at the start of the round called Toxic Screen Equip a gas emitter launcher. Fire to deploy a long line of gas emitters. Re-use the ability to create a tall wall of toxic gas at the cost of fuel. This ability can be re-used more than once. You also have an Ultimate Ability called Viper’s Pit, which charges up from kills, you can also purchase two more abilities called Snake Bite and Poison Cloud between rounds.',
    '100', 
    '200', 
    'Free', 
    '7 Points', 
    'Equip a chemical launcher. Fire to launch a canister that shatters upon hitting the floor, creating a lingering chemical zone that damages and slows enemies. Fire a projectile that explodes into a pool of damaging acid.', 
    'Equip a gas emitter. Fire to throw the emitter that perpetually remains throughout the round. Re-use the ability to create a toxic gas cloud at the cost of fuel. This ability can be re-used more than once and can be picked up to be redeployed. 4 Second internal Cooldown Vipers Abilities cause Decay Damage, rapidly deals non-lethal damage until 1 HP and 1 Armor. Leaving the poison allows players to rapidly regenerate HP back to the original amount before entering the poison. Viper is Immune to her own poison. Throw a gas emitter that you can reactivate to create a poisonous smoke cloud at the cost of fuel. The emitter can be picked up and thrown again after a short cooldown.', 
    'Equip a gas emitter launcher. Fire to deploy a long line of gas emitters. Re-use the ability to create a tall wall of toxic gas at the cost of fuel. This ability can be re-used more than once. 4 Second internal Cooldown. Deploy a long line of gas emitters that you can reactivate to create a tall wall of toxic gas at the cost of fuel.', 
    'Equip a chemical sprayer. Fire to spray a chemical cloud in all directions around Viper, creating a large cloud that reduces the vision range and maximum health of players inside of it. Emit a massive toxic cloud in a large area that lasts as long as Viper stays inside the cloud. Enemies inside the cloud are highlighted to Viper.', 
    'res/Viper_PoisonCloud.png',
    'res/Viper_SnakeBite.png',
    'res/Viper_ToxicScreen.png',
    'res/Viper_ViperPit.png',
    'Snake Bite', 
    'Poison Cloud', 
    'Toxic screen', 
    'Vipers pit',
    3.5,
    'res/breach.jpg',
    'res/Brimstone.jpg',
    'res/sova.jpg',

    'res/sage.jpg',
    'res/Brimstone.jpg',

    'res/White.png',
    2,
    1,
    1,
    1,   ),

    Character('Omen', 
    'Controller',
    'C Tier',
    '????',
    'res/omen.jpg',
    'Valorant Omen Signature Ability available at the start of the round called Dark Cover Equip a shadow orb and see its range indicator. Fire to throw the shadow orb to the marked location, creating a long-lasting shadow sphere that blocks vision. Hold Alternate Fire while targeting to move the marker further away. Hold the ability key with targeting to move the market closer. You also have an Ultimate Ability called From the Shadows, which charges up from kills, you can also purchase two more abilities called Shrouded Step and Paranoia between rounds.', 
    '100', 
    '200', 
    'Free', 
    '7 Points', 
    'Equip a shadow walk ability and see its range indicator. Fire to begin a brief channel, then teleport to the marked location. After a delay, dematerialize and teleport a short distance.', 
    'Instantly fire a shadow projectile forward, briefly reducing the vision range of all players it touches. This projectile can pass straight through walls. Send out an Ethereal shadow in a straight line, Near sighting anyone it touches.', 
    'Equip a shadow orb and see its range indicator. Fire to throw the shadow orb to the marked location, creating a long-lasting shadow sphere that blocks vision. Hold Alternate Fire while targeting to move the marker further away. Hold the ability key with targeting to move the market closer. Cooldown: 30 Seconds You can use it in combination with your ultimate ability From the Shadows and Teleport inside the Smoke safely. Cast out a stealthed ethereal orb that bursts into an obscuring sphere of shadow at its final location. Can be charged to increase distance.', 
    'Equip a tactical map. Fire to begin teleporting to the selected location. While teleporting, Omen will appear as a Shade that can be destroyed by an enemy to cancel his teleport. Select anywhere on the map to teleport and reform. When arriving, appear as a Shade, that will go back to your original location if killed. Once the teleport is complete, become Incorporeal for a short time.', 
    'res/Omen_DarkCover.png',
    'res/Omen_FromtheShadows.png',
    'res/Omen_Paranoia.png',
    'res/Omen_ShroudedStep.png',
    'Shrouded Step', 
    'Paranoia', 
    'Dark cover', 
    'From the shadows',
    3.5, 
    'res/cypher.jpg',

    'res/White.png',
    'res/White.png',

    'res/Brimstone.jpg',

    'res/White.png',
    'res/White.png',
    2,
    1,
    2,
    1,  ),


  ];

